--Scenario 1: UpdateCustomerLastModified
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/
UPDATE Customers
SET Balance = 2000
WHERE CustomerID = 1;

COMMIT;

SELECT * FROM Customers;

--Scenario 2: LogTransaction
CREATE TABLE TransactionLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO TransactionLog
    (TransactionID, LogDate)
    VALUES
    (:NEW.TransactionID, SYSDATE);
END;
/
INSERT INTO Transactions
VALUES
(3, 1, SYSDATE, 500, 'Deposit');

COMMIT;

SELECT * FROM TransactionLog;

--Scenario 3: CheckTransactionRules
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN
    IF :NEW.TransactionType = 'Withdrawal' THEN

        SELECT Balance
        INTO v_balance
        FROM Accounts
        WHERE AccountID = :NEW.AccountID;

        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(
                -20003,
                'Insufficient account balance'
            );
        END IF;

    END IF;
END;
/
INSERT INTO Transactions
VALUES
(4, 1, SYSDATE, 50000, 'Withdrawal');

